  <div class="backgroundimage"> <!--Background image was created using GenAI-->
  <div class="container">  <!-- Main content wrapper -->
      <header class="site-header"> <!-- Page header section -->
          <!--The image sourced for our logo was created using generative AI-->
          <img src="images/logo1-transparent.png" alt="Nexa-Soft Logo" class="logo"> <!-- Displays company logo -->
      </header>
  