<div id="navbar"> <!-- Navigation bar starts -->
  <!--This navigation menu allows the user to use hyperlinks to direct them to the desired page-->
  <!-- Navigation links list -->
  <a href="index.php">Home</a> <!-- Link to homepage -->
  <a href="jobs.php">Job Descriptions</a> <!-- Link to jobs page -->
  <a href="apply.php">Apply</a> <!-- Link to apply page -->
  <a href="about.php">About us</a> <!-- Link to about page -->
  <a>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;Thank you for using this site</a>
</div>

