
<body> <!-- Page content starts -->
    

    <main> <!-- Main content section -->
        <section class="about"> <!-- About section starts -->
            <h1 class="Capsule">About Nexa-Soft Technologies</h1> <!-- Section heading -->
            <ul> <!-- Description list -->
        <li>
            <!--Sections of the our companys desrciption was created using generative AI-->
            <strong>Nexa-Soft Technologies - Innovating the future:</strong> 
            At NexaSoft Technologies, we do not just build software
            we craft digital experiences. Our team of passionate
            developers, engineers, and designers harness cutting-edge 
            technology to create innovative, scalable, and high-performance solutions.
            From AI-driven applications to enterprise-level software,
            we push the boundaries of what is possible.
            Join us on this exciting journey as we redefine the future of technology!
        </li>
        </ul>
    </section>

    <section>
        <img src="styles/images/codingimage.jpg" alt="Group Photo" class="image1"/>
    </section>

    <section>
        <img src="styles/images/robots.jpg" alt="Group Photo" class="image2"/>
    </section>

    <!--The Services listed were partially created using generative AI-->
    <section class="services"> <!-- Services section starts -->
        <h1 class="Capsule">Our Services</h1> <!-- Services heading -->
        <ul> <!-- Services list -->
            <li>
                <strong>Custom Software Development:</strong> <!-- Service title -->
                We build tailor-made software solutions that align perfectly with your business goals
                whether it is enterprise applications, SaaS platforms, or internal systems.
            </li>
            <li>
            <strong>AI and Machine Learning Integration:</strong> 
            Leverage artificial intelligence to automate tasks, gain insights,
            and drive smarter decision-making. From chatbots to predictive analytics, we have got you covered.
            </li>
            <li>
                <strong>Mobilee and Web App Development:</strong> 
                We design and develop sleek, user-friendly, and high-performance apps
                across iOS, Android, and web platforms—optimized for both functionality and user experience.  
            </li>
            <li>
                <strong>Cloud Solutions & DevOp Services</strong> 
                Scale your operations with secure and flexible cloud-based infrastructure.
                Our DevOps services ensure fast, reliable deployment and continuous integration for agile development.
            </li>
        </ul>
    </section>

    <section class="job-offers"> <!-- Job offers section -->
        <!--The Job Offers listed were partially created using generative AI-->
        <h1 class="Capsule">Latest Job Offers</h1> <!-- Job section heading -->
        
        <section class="joboffersminicapsule">
        <ul>
           <li>
            <strong>IT Support Technician:</strong> <!-- Job title -->
            As an IT Support Technician, you will be the first point of contact for technical support within the organization.
            You’ll help diagnose, troubleshoot, and resolve hardware and software issues while ensuring optimal performance of IT systems.
            This is a key role for maintaining productivity and smooth IT operations in a fast-paced environment.
           </li>
           <li>
            <strong>Junior Network Administrator:</strong>
            As a Junior Network Administrator, you will support the installation, configuration, and maintenance of the organization's network infrastructure. 
            You will assist in monitoring systems, identifying bottlenecks, and resolving issues to ensure optimal network performance and security.
           </li>
        </ul>
        </section>
    </section>

    <section> <img src="styles/images/REALTRANSPARENTIMAGE.png" alt="plus sign image" class="image3"/> </section>

    <section class="news"> <!-- News section starts -->
        <h1 class="Capsule">News & Updates</h1> <!-- News section heading -->
        <ul>
            <li>
                <strong>April 2025:</strong> 
                Nexa-Soft Technologies has launched its new internship program
                with Swinburne University giving computer science graduates an oppurtunity to show their software
                development skills and apply them in the real world. 
            </li>
            
            <li>
                <strong>January 2025:</strong> 
                Our team at Nexa-Soft Technologies has sucessfully
                stopped and mitigating the damage of a cyber threat from an unknown source. All user data
                has been preserved. 
            </li>

            <li>
                <strong>Novemeber 2024:</strong> 
                Nexa-Soft Technologies announces its collabration with a new cloud hosting
                platform, offering enhanced speed and security features. 
            </li>
        </ul>
    </section>

    <section class="history"> <!--History section starts-->
        <h1 class="Capsule"> Our Histroy</h1> <!--History section heading-->
        <ul>
            <li>
                <strong>The foundation of Nexa-Soft Technologies:</strong> <!--The history was created using generative AI-->
                Nexa-Soft Technologies was founded by a group of visionary developers and engineers who shared a passion for innovation and excellence in software design. 
                What began as a small startup in a co-working space quickly gained traction through its groundbreaking AI-driven solutions and custom enterprise software. 
                The company’s commitment to quality, user experience, and future-focused technology attracted major clients across industries. 
                Through strategic partnerships and a relentless drive to push boundaries, Nexa-Soft rapidly scaled, becoming a leading force in digital transformation worldwide.
            </li>
        </ul>
    </section>
    </main>
    <footer> <!-- Footer section -->
        <!--The footer directs users to the groups GitHub page/Jira Project as well as our email addresses-->
        <div class="footer"> <!-- Footer content block -->
            <p>Find us on <a href="https://github.com/JoseHTy/GroupProjectWeek07">GitHub</a></p> <!-- GitHub link -->
            <p>Check out our <a href="https://student-team-as56fp2b.atlassian.net/jira/software/projects/WTGA/summary">Jira Project</a></p> <!-- Jira link -->
        </div>
        <div class="contact"> <!-- Contact link container -->
            <a href="mailto:103644281@student.swin.edu.au" class="button">Contact Us</a> <!-- Email link -->
        </div>
    </footer>
</div>
</body>
</html>