  <footer> <!-- Footer section -->
        <!--The footer directs users to the groups GitHub page/Jira Project as well as our email addresses-->
        <div class="footer"> <!-- Footer content block -->
            <p>Find us on <a href="https://github.com/JoseHTy/GO1-COS5_part2">GitHub</a></p> <!-- GitHub link -->
            <p>Check out our <a href="https://student-team-as56fp2b.atlassian.net/jira/software/projects/WTGA/summary">Jira Project</a></p> <!-- Jira link -->
        </div>
        <div class="contact"> <!-- Contact link container -->
            <a href="mailto:103644281@student.swin.edu.au" class="button">Contact Us</a> <!-- Email link -->
        </div>
    </footer>